### ISSUE TITLE
Script to add control features

### ISSUE THREAD

**Issue by t-davidson** [cttong/info6742#11]
To assess the robustness of our findings we will probably need to run a model where we also include controls. Think about basic controls like word counts, avg word lengths, reading level, sentiment, POS tags, tokens. I have scripts [here](https://github.com/t-davidson/hate-speech-and-offensive-language) that can be easily modified to do much of this work.

**Comment by cttong** [comment]
Just read this - forgot to add most of these but I have a version of the pickle file I can upload later if you want that contains the text of each post (though its a much bigger file)

**Comment by t-davidson** [comment]
No need for a duplicate, we can just parse the original file again if we need to.

**Comment by t-davidson** [comment]
Closing for now. We can pursue this if we want to do a more rigorous analysis at some point.
